name: summittrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+20

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  google_sign_in: 6.1.6
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.4
  http: ^1.2.2
  image_picker: ^1.1.2
  image_picker_android: ^0.8.13+1
  image_picker_platform_interface: ^2.11.1
  shared_preferences: ^2.3.2
  video_player: ^2.9.5
  geolocator: ^12.0.0
  maplibre_gl: ^0.24.1
  cloud_functions: ^4.7.6
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^4.1.1
  crypto: ^3.0.3
  
  share_plus: ^10.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  app_links: ^6.4.1
  firebase_database: ^10.5.7
  google_maps_flutter: ^2.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# 🔒 Dito natin pinipilit ang tamang iOS plugin version para tumugma sa Firebase
dependency_overrides:
  google_maps_flutter_android: 2.14.2
  google_sign_in_ios: 5.7.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/apo.jpg
    - assets/images/mayon_home.png
    - assets/images/sta_cruz_sibulan_trail.png
    - assets/images/mt_apo_enhanced.png
    - assets/images/mt_batulao_home.png
    - assets/images/mt_pulag_home.jpg
    - assets/images/mt_ulap.jpg
    - assets/images/mt_daraitan_home.png
    - assets/images/mt_maculot_home.png
    - assets/images/mt_pico_de_loro_home.png
    - assets/images/mt_pinatubo_home.png
    - assets/images/mt_guiting_guiting_home.png
    - assets/images/mt_gulugod_baboy_home.png
    - assets/images/mt_manoyba_home.png
    - assets/images/mt_arayat_home.png
    - assets/images/mt_makiling_home.png
    - assets/images/mt_tugew_home.png
    - assets/images/mt_mariglem_home.png
    - assets/images/logo.jpg
    - assets/images/mt apo.jpg
    - assets/videos/
    - assets/images/first_aid/