// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVhWIwbGAQO-_rVdZsa4liL0N21eP-h4c',
    appId: '1:785993329168:web:f91e18ef6a640e7b1cf895',
    messagingSenderId: '785993329168',
    projectId: 'summittrack-10481',
    authDomain: 'summittrack-10481.firebaseapp.com',
    storageBucket: 'summittrack-10481.firebasestorage.app',
    measurementId: 'G-901F0M0W59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBobG-HXLwhvyXFQaczZY1vdU-Kas7ExNo',
    appId: '1:785993329168:android:e62297fd24d49b3b1cf895',
    messagingSenderId: '785993329168',
    projectId: 'summittrack-10481',
    storageBucket: 'summittrack-10481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZzUIq1ODM3oVnOmKlSdoTiYZneXjjraY',
    appId: '1:785993329168:ios:78152ff9e916b9771cf895',
    messagingSenderId: '785993329168',
    projectId: 'summittrack-10481',
    storageBucket: 'summittrack-10481.firebasestorage.app',
    iosBundleId: 'com.example.summittrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZzUIq1ODM3oVnOmKlSdoTiYZneXjjraY',
    appId: '1:785993329168:ios:78152ff9e916b9771cf895',
    messagingSenderId: '785993329168',
    projectId: 'summittrack-10481',
    storageBucket: 'summittrack-10481.firebasestorage.app',
    iosBundleId: 'com.example.summittrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVhWIwbGAQO-_rVdZsa4liL0N21eP-h4c',
    appId: '1:785993329168:web:11ffca8d532daa611cf895',
    messagingSenderId: '785993329168',
    projectId: 'summittrack-10481',
    authDomain: 'summittrack-10481.firebaseapp.com',
    storageBucket: 'summittrack-10481.firebasestorage.app',
    measurementId: 'G-TNHX1R9M7V',
  );
}
