name: Build Unsigned iOS App

on:
  push:
    branches: [ main, master, Migration ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        working-directory: SummitTrack-Front-End
        run: flutter pub get

      - name: Build Unsigned iOS App
        working-directory: SummitTrack-Front-End
        run: flutter build ios --release --no-codesign

      - name: Package Payload to .ipa
        working-directory: SummitTrack-Front-End
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r -9 MyApp.ipa Payload

      - name: Upload .ipa Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App-IPA
          path: SummitTrack-Front-End/build/ios/iphoneos/MyApp.ipa